name: CI
on:
  - pull_request
  - push
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Compile Elm sources
        run: elm make src/Main.elm --optimize --output=public/js/main.js

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install elm-test
        run: npm install elm-test

      - name: Run tests
        run: npx elm-test
